<?php
/**
 * Created by PhpStorm.
 * User: EDGAR
 * Date: 04/06/2015
 * Time: 10:49 AM
 */

use Illuminate\Database\Seeder;

class CityTableSeeder extends Seeder {

    public function run()
    {
        $tasks = [
            ['name' => 'El Encanto', 'county_id' => 1,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'La Chorrera', 'county_id' => 1,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'La Pedrera', 'county_id' => 1,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'La Victoria', 'county_id' => 1,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Leticia', 'county_id' => 1,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Mirití-Paraná', 'county_id' => 1,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Puerto Alegría', 'county_id' => 1,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Puerto Arica', 'county_id' => 1,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Puerto Nariño', 'county_id' => 1,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Puerto Santander', 'county_id' => 1,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Tarapacá', 'county_id' => 1,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Abejorral', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Abriaquí', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Alejandría', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Amagá', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Amalfi', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Andes', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Angelópolis', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Angostura', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Anorí', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Antioquia', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Anzá', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Apartadó', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Arboletes', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Argelia', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Armenia', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Barbosa', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Bello', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Belmira', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Betania', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Betulia', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Bolívar', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Briceño', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Buriticá', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Cáceres', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Caicedo', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Caldas', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Campamento', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Cañasgordas', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Caracolí', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Caramanta', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Carepa', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Carmen de Viboral', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Carolina del Príncipe', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Caucasia', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Chigorodó', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Cisneros', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Cocorná', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Concepción', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Concordia', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Copacabana', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Dabeiba', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Donmatías', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Ebéjico', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'El Bagre', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'El Peñol', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'El Retiro', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'El Santuario', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Entrerríos', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Envigado', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Fredonia', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Frontino', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Giraldo', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Girardota', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Gómez Plata', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Granada', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Guadalupe', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Guarne', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Guatapé', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Heliconia', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Hispania', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Itagüí', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Ituango', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Jardín', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Jericó', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'La Ceja', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'La Estrella', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'La Pintada', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'La Unión', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Liborina', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Maceo', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Marinilla', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Medellín', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Montebello', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Murindó', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Mutatá', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Nariño', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Nechí', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Necoclí', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Olaya', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Peque', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Pueblorrico', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Puerto Berrío', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Puerto Nare', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Puerto Triunfo', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Remedios', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Rionegro', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Sabanalarga', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Sabaneta', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Salgar', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'San Andrés de Cuerquia', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'San Carlos', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'San Francisco', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'San Jerónimo', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'San José de la Montaña', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'San Juan de Urabá', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'San Luis', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'San Pedro de los Milagros', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'San Pedro de Urabá', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'San Rafael', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'San Roque', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'San Vicente', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Santa Bárbara', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Santa Rosa de Osos', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Santo Domingo', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Segovia', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Sonsón', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Sopetrán', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Támesis', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Tarazá', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Tarso', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Titiribí', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Toledo', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Turbo', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Uramita', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Urrao', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Valdivia', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Valparaíso', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Vegachí', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Venecia', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Vigía del Fuerte', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Yalí', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Yarumal', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Yolombó', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Yondó', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Zaragoza', 'county_id' => 2,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Arauca', 'county_id' => 3,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Arauquita', 'county_id' => 3,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Cravo Norte', 'county_id' => 3,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Fortul', 'county_id' => 3,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Puerto Rondón', 'county_id' => 3,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Saravena', 'county_id' => 3,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Tame', 'county_id' => 3,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Baranoa', 'county_id' => 4,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Barranquilla', 'county_id' => 4,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Campo de la Cruz', 'county_id' => 4,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Candelaria', 'county_id' => 4,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Galapa', 'county_id' => 4,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Juan de Acosta', 'county_id' => 4,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Luruaco', 'county_id' => 4,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Malambo', 'county_id' => 4,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Manatí', 'county_id' => 4,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Palmar de Varela', 'county_id' => 4,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Piojó', 'county_id' => 4,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Polonuevo', 'county_id' => 4,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Ponedera', 'county_id' => 4,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Puerto Colombia', 'county_id' => 4,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Repelón', 'county_id' => 4,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Sabanagrande', 'county_id' => 4,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Sabanalarga', 'county_id' => 4,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Santa Lucía', 'county_id' => 4,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Santo Tomás', 'county_id' => 4,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Soledad', 'county_id' => 4,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Suán', 'county_id' => 4,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Tubará', 'county_id' => 4,'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['name' => 'Usiacurí', 'county_id' => 4,'created_at' => new DateTime, 'updated_at' => new DateTime],
        ];
        DB::table('cities')->insert($tasks);
    }
}